### PR TITLE
Add checkVariance function

### PR DESCRIPTION
**Pull request by zackhsi**

### CODE REVIEW

**Comment by mleventi** [comment]
+1

**Comment by zackhsi** [comment]
:rocket:

**Comment by lyft-buildnotify** [comment]
Submit queue bot says: Your commit has been enqueued for commit to master followed by a test run. I will close and update this PR once tests have passed and your code is ready for deployment...

**Comment by lyft-buildnotify** [comment]
Submit queue rebase failure:
- Please see job URL: https://jenkins.lyft.net/job/submit_queue_rebase/4201/

**Pull request merged**
