### PR TITLE
[SQ MERGED] Allow max data points to be configurable along with failure threshold

### PR DESCRIPTION
**Pull request by yashsarma**
cc @paulnivin 
screen shot 2016-01-03 at 2 36 02 pm

### CODE REVIEW

**Comment by paulnivin** [comment]
:+1:

**Comment by zackhsi** [comment]
+1

**Comment by yashsarma** [comment]
:rocket:

**Comment by lyft-buildnotify** [comment]
Submit queue bot says: Your commit has been enqueued for commit to master followed by a test run. I will close and update this PR once tests have passed and your code is ready for deployment...

**Comment by lyft-buildnotify** [comment]
Commit: https://github.com/lyft/grafana/commit/ce2d2b73681b1d798e03323108546440412b23c9
Job URL: https://jenkins.lyft.net/job/submit_queue_rebase/10990/

_Your PR has been rebased and pushed to master. This PR has been closed and is referenced by the master commit. The branch has been deleted._

If you need to revert your commit, type '_:sob:_' in a comment.

If you need to make a hotfix on top of the latest deployed revision, type '_submit this please to hotfix branch_' in a comment.

If you need to cherry-pick this into a release branch, type '_:cherries: into `branch_name`_' in a comment

Need more help? Look [here](https://github.com/lyft/ops/blob/master/buildnotify/Submit_Queue.md).

**Pull request closed without merging**
